"""Table updatestokharian

Revision ID: 3580091ed900
Revises: e2c75087f25c
Create Date: 2026-01-20 09:35:35.440193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3580091ed900'
down_revision: Union[str, Sequence[str], None] = 'e2c75087f25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_stok_harian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_menu', sa.Integer(), nullable=False),
    sa.Column('jumlah_porsi', sa.Integer(), nullable=False),
    sa.Column('tanggal_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_menu'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_stok_harian_id'), 'update_stok_harian', ['id'], unique=False)
    op.add_column('menu', sa.Column('foto', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('deskripsi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'deskripsi')
    op.drop_column('menu', 'foto')
    op.drop_index(op.f('ix_update_stok_harian_id'), table_name='update_stok_harian')
    op.drop_table('update_stok_harian')
    # ### end Alembic commands ###
