"""drop column foto

Revision ID: 3a642b8bb947
Revises: de05ffed049d
Create Date: 2026-02-02 12:14:45.738949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a642b8bb947'
down_revision: Union[str, Sequence[str], None] = 'de05ffed049d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('kv_store_4b315d27_key_idx'), table_name='kv_store_4b315d27', postgresql_ops={'key': 'text_pattern_ops'})
    op.drop_table('kv_store_4b315d27')
    op.drop_column('menu', 'foto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('foto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('kv_store_4b315d27',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('kv_store_4b315d27_pkey'))
    )
    op.create_index(op.f('kv_store_4b315d27_key_idx'), 'kv_store_4b315d27', ['key'], unique=False, postgresql_ops={'key': 'text_pattern_ops'})
    # ### end Alembic commands ###
