"""Perbaikan relasi antar table

Revision ID: 7530c7783db3
Revises: 97ac90dae80e
Create Date: 2026-01-21 08:45:18.870803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7530c7783db3'
down_revision: Union[str, Sequence[str], None] = '97ac90dae80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('id_kategori_menu', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('menu_kategori_fkey'), 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'kategori_menu', ['id_kategori_menu'], ['id'])
    op.drop_column('menu', 'kategori')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('kategori', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.create_foreign_key(op.f('menu_kategori_fkey'), 'menu', 'kategori_menu', ['kategori'], ['id'])
    op.drop_column('menu', 'id_kategori_menu')
    # ### end Alembic commands ###
