"""penambahan table kategorimenu

Revision ID: 97ac90dae80e
Revises: 8ca2f6bdff45
Create Date: 2026-01-20 16:40:48.398462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97ac90dae80e'
down_revision: Union[str, Sequence[str], None] = '8ca2f6bdff45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kategori', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_kategori')
    )
    op.create_index(op.f('ix_kategori_menu_id'), 'kategori_menu', ['id'], unique=False)
    # Insert the enum values into kategori_menu
    op.execute("INSERT INTO kategori_menu (nama_kategori) VALUES ('makanan'), ('minuman'), ('makanan_ringan')")
    # Alter the column with USING to convert enum to integer
    op.alter_column('menu', 'kategori',
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="CASE WHEN kategori = 'makanan' THEN 1 WHEN kategori = 'minuman' THEN 2 WHEN kategori = 'makanan_ringan' THEN 3 END")
    op.create_foreign_key(None, 'menu', 'kategori_menu', ['kategori'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.alter_column('menu', 'kategori',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('makanan', 'minuman', 'makanan_ringan', name='kategorimenu'),
               existing_nullable=False)
    op.drop_index(op.f('ix_kategori_menu_id'), table_name='kategori_menu')
    op.drop_table('kategori_menu')
    # ### end Alembic commands ###
