"""revisin kolom table

Revision ID: de05ffed049d
Revises: 7530c7783db3
Create Date: 2026-01-24 08:13:11.663185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de05ffed049d'
down_revision: Union[str, Sequence[str], None] = '7530c7783db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'no_telp')
    op.drop_column('user', 'nama')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('no_telp', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
