"""Inisiasi table ulang

Revision ID: e2c75087f25c
Revises: 
Create Date: 2026-01-20 09:29:05.171915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c75087f25c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karyawan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_karyawan', sa.String(), nullable=False),
    sa.Column('no_hp', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_karyawan_id'), 'karyawan', ['id'], unique=False)
    op.create_table('meja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_meja', sa.String(), nullable=False),
    sa.Column('kapasitas', sa.Integer(), nullable=False),
    sa.Column('lokasi', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('tersedia', 'booked', name='statusmeja'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_meja')
    )
    op.create_index(op.f('ix_meja_id'), 'meja', ['id'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_menu', sa.String(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.Enum('makanan', 'minuman', 'makanan_ringan', name='kategorimenu'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_menu')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_id'), 'transaksi', ['id'], unique=False)
    op.create_table('pembayaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_transaksi', sa.Integer(), nullable=False),
    sa.Column('metode', sa.Enum('cash', 'qris', name='metodepembayaran'), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('waktu_bayar', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_transaksi'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_transaksi')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('no_telp', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'pramusaji', 'manager', 'kasir', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='statususer'), nullable=True),
    sa.Column('id_karyawan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_karyawan'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('pesanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_transaksi', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_meja', sa.Integer(), nullable=True),
    sa.Column('tipe_pesanan', sa.Enum('dine_in', 'takeaway', name='tipepesanan'), nullable=False),
    sa.Column('kode_pesanan', sa.String(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('dipesan', 'diproses', 'selesai', 'dibayar', 'dibatalkan', name='statuspesanan'), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_meja'], ['meja.id'], ),
    sa.ForeignKeyConstraint(['id_transaksi'], ['transaksi.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_pesanan')
    )
    op.create_index(op.f('ix_pesanan_id'), 'pesanan', ['id'], unique=False)
    op.create_table('detail_pesanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pesanan', sa.Integer(), nullable=False),
    sa.Column('id_menu', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_menu'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['id_pesanan'], ['pesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detail_pesanan_id'), 'detail_pesanan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detail_pesanan_id'), table_name='detail_pesanan')
    op.drop_table('detail_pesanan')
    op.drop_index(op.f('ix_pesanan_id'), table_name='pesanan')
    op.drop_table('pesanan')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('pembayaran')
    op.drop_index(op.f('ix_transaksi_id'), table_name='transaksi')
    op.drop_table('transaksi')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_meja_id'), table_name='meja')
    op.drop_table('meja')
    op.drop_index(op.f('ix_karyawan_id'), table_name='karyawan')
    op.drop_table('karyawan')
    # ### end Alembic commands ###
